# Generated by Django 3.1.3 on 2021-02-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigscopy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
